run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gofmt
    - goimports
    - gocritic
    - ineffassign
    - bodyclose
    - dupl
    - gocyclo
    - goconst
    - gosec
    - gosimple
    - lll
    - misspell
    - nakedret
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - revive
    - copyloopvar

issues:
  exclude-use-default: false